services:
  app:
    image: nvcr.io/nvidia/pytorch:24.10-py3
    # 作業フォルダ設定（コンテナ内）
    working_dir: /image_genai
    # ─── マウント ──────────────────────────────────────────
    volumes:
      # compose.yml のあるディレクトリ全体を /image_genai にマウント
      - .:/image_genai
      - ./ComfyUI:/image_genai/ComfyUI
      - /tmp/.X11-unix:/tmp/.X11-unix            # ← X11 Unix ソケット共有
      - ${HOME}/.Xauthority:${HOME}/.Xauthority:ro  # 認証 cookie

    # ─── GPU ランタイム ───────────────────────────────────
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ["gpu"]

    # ─── 環境変数 ────────────────────────────────────────
    environment:
      - DISPLAY=:0                                # Unix ソケットを使う
      - XAUTHORITY=${HOME}/.Xauthority
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all

    # ─── コマンド ────────────────────────────────────────
    command: ["/bin/bash", "-c", "sleep infinity"]  # デバッグ用に常駐

    # ─── ポート公開 ──────────────────────────────────────
    ports:
      - "8188:8188"                                # host:container

    # ─── Compose ネットワーク ────────────────────────────
    networks:
      my-network:
        aliases:
          - img_genai

networks:
  my-network:
