services:
  app:
    image: pytorch/pytorch:2.1.2-cuda11.8-cudnn8-devel
    container_name: image_genai_app
    working_dir: /image_genai
    gpus: all
    environment:
      - TZ=Asia/Tokyo
      - DISPLAY=:0
      - XAUTHORITY=${HOME}/.Xauthority
      - PIP_DISABLE_PIP_VERSION_CHECK=1
      - PYTHONUNBUFFERED=1
      - XFORMERS_DISABLED=1
    volumes:
      - .:/image_genai
      - ./image_genai/data:/data
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.Xauthority:${HOME}/.Xauthority:ro
    command: bash -c "./setup_comfyui.sh && sleep infinity"
    ports:
      - "8190:8190"
    restart: unless-stopped
