services:
  app:
    image: nvcr.io/nvidia/pytorch:24.10-py3

    # コンテナ起動時の作業ディレクトリ
    working_dir: /image_genai

    # ─── マウント ──────────────────────────────────────────
    volumes:
      # compose.yml のあるディレクトリ全体をマウント
      - .:/image_genai
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.Xauthority:${HOME}/.Xauthority:ro

    # ─── GPU ランタイム ───────────────────────────────────
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ["gpu"]

    # ─── 環境変数 ────────────────────────────────────────
    environment:
      - DISPLAY=:0
      - XAUTHORITY=${HOME}/.Xauthority
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all

    # ─── コマンド ────────────────────────────────────────
    command: ["/bin/bash", "-c", "sleep infinity"]

    # ─── ポート公開 ──────────────────────────────────────
    ports:
      - "8188:8188"

    # ─── Compose ネットワーク ────────────────────────────
    networks:
      my-network:
        aliases:
          - img_genai

networks:
  my-network:
